[GLOBAL]
pants_version = "2.17.0"
backend_packages = [
    "pants.backend.python",
]
pants_ignore = [
    "venv/"
]

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]

[python]
# The default interpreter constraints for code in this repo. Individual targets can override
#  this with the `interpreter_constraints` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.
#
# It's usually a good idea to pin this to a particular version, e.g. `==3.9.*`. We only use a range
# so that this example works on many different machines.
#
# If you use Apple Silicon, set to a value like `>=3.9`.
interpreter_constraints = [">=3.9,<3.10"]

# tell pants not to ignore __init__.py files
# https://www.pantsbuild.org/docs/python-backend
tailor_ignore_empty_init_files = false